### ISSUE TITLE
User Interface is Partial When HiDPI Mode is Enabled in Ableton

### ISSUE THREAD

**Issue by Nevodev** [tiagolr/gate1#1]
https://github.com/tiagolr/gate1/assets/51047891/62046e3d-6a01-4aa7-8b99-ab6744ec7b43

When Auto Scale Plug-In Window is not ticked, the UI will be partial and unusable.
![image](https://github.com/tiagolr/gate1/assets/51047891/419031b2-fbc9-4b13-a5c3-db454218e98d)
![image](https://github.com/tiagolr/gate1/assets/51047891/f46899d5-5a52-4b3b-ae81-f4f893235e61)
![image](https://github.com/tiagolr/gate1/assets/51047891/40244a6b-e095-4aee-863a-5d0bba453e17)

**Comment by tiagolr** [comment]
Thanks for reporting, seems not easy to solve but will try.

**Comment by tekord** [comment]
The same issue in Reaper. I have higher DPI in OS

**Comment by tiagolr** [comment]
Its been fixed I think, I'm just waiting on some confirmations that there are no side issues before publishing a fixed version.

**Comment by Nevodev** [comment]
> Its been fixed I think, I'm just waiting on some confirmations that there are no side issues before publishing a fixed version.

I can help you test it. Maybe you can send a fixed version to me? 😊

**Comment by tiagolr** [comment]
Sure, I just deployed HighDPI support for GATE1 (version 1.0.4) and TIME1 (version 1.0.2), closing this, please download latest version and let me know of any issues, thanks a lot!
