### ISSUE TITLE
MIDI mode doesn't seem to be working

### ISSUE THREAD

**Issue by cloph-dsp** [tiagolr/gate1#2]
I use Mixcraft, and I've tried it both in audio channels, midi instrument channels and a sub channel with a midi dependence, it doesn't seem to recognize the midi notes input

**Comment by tiagolr** [comment]
Midi notes should trigger the envelope when MIDI mode is set.
I'll test soon, maybe its an issue with Mixcraft + Gate1, meanwhile let me know if you find a workaround or that some setting was off or that it works in other DAW like Reaper.

**Comment by kastru** [comment]
thanks for answering @tiagolr. great plugin, cheers

---

the problem seems related to channel selection settings, especially with "omni"
- setting it to "off" or a number triggers one selected gate, with any note (working as it should)
- if set to 1, it doesn't play anything
- if set to omni, it recognizes gate shifts but doesn't play them, only shows the shift visually

think the settings names might be shifted?

**Comment by cloph-dsp** [comment]
thanks for answering @tiagolr. great plugin, cheers

---

the problem seems related to channel selection settings:
- setting it to "off" or a number triggers one selected gate with any note (working as it should)
- if set to omni or 1, it recognizes gate shifts but doesn't play anything, only shows the different gates visually
- it seems to default to 10, which I assume wasn't supposed to happen

think the settings might be shifted or a setting option added?

**Comment by tiagolr** [comment]
I am not sure if you are trying to trigger the envelope or switch the pattern selected.

There is a button on main window (MIDI) that when activated midi notes trigger the envelope.
On the other hand there is a MIDI channel trigger (default chn 10) where notes on that channel trigger a different pattern (C to B notes trigger patterns 1 to 12).

Which MIDI trigger are you trying to use? Triggering envelope or select a different pattern? Also what is the problem exactly - it may be that midi notes are not passing through, try placing the GATE FX after the synth that you want midi notes to reach, may fix the problem but it may be something indeed I have to fix: midi passthrough.

**Comment by cloph-dsp** [comment]
oh ok sorry, nvm, I misunderstood how it works. I was trying to do both and thought playing C3 then C#3 would trigger gate 1 then gate 2. now I understand that the midi notes trigger and the midi gate switch are different modes meant for different purposes. thanks for explaining. i got it to work now by sending different notes through different channels.

i'm not sure about midi passthrough. I was applying the effect to an audio clip and using midi just as a trigger.

**Comment by tiagolr** [comment]
Great to hear that! Yes they are different modes and should be used as you said through different channels, maybe I should review the documentation. Regards.
